.flake8, .github/workflows/black.yml, .github/workflows/flake8.yml, .github/workflows/isort.yml, .github/workflows/mypy.yml, .github/workflows/pylint.yml, .github/workflows/shellcheck.yml, .github/workflows/test.yml, .isort.cfg, .mypy.ini, .pylintrc, pyproject.toml
Hi @YPCrumble, this PR is used for initial adding Github actions check.
I will merge this in develop.
=> Initial add github actions

accounts/forms.py, accounts/models.py, guppy/asgi.py, guppy/urls.py, guppy/wsgi.py, manage.py, requirements/local.txt, search/apps.py, search/forms.py, search/tests.py, search/urls.py, search/views.py, settings/base.py
Hi @YPCrumble, this PR is used for adding Black code formatter.
I will merge this in.
=> Add Black code formatter

accounts/models.py, accounts/views.py, guppy/urls.py, requirements/local.txt
Hi @YPCrumble, this PR is used for adding isort check.
I'll merge this in.
=> Update isort check

accounts/factories.py, accounts/tests.py, accounts/urls.py, accounts/views.py, requirements/base.txt, settings/base.py
Hi @YPCrumble, this PR is used for adding rest_framework and APIs for auth.
Please help me to review and merge.
=> Add rest framework and auth

requirements/base.txt, settings/base.py
Hi @YPCrumble, this PR is used for adding Postgres SQL.
Please help me to review and merge.
=> Setup database to use postgres

search/templates/search/search.html, search/urls.py, search/views.py
Hi @YPCrumble, this PR is used for adding dummy placeholder search results page.
=> Add dummy placeholder search results page

accounts/models.py, accounts/tests.py, accounts/views.py, search/factories.py
Hi @YPCrumble, this PR is used for getting profile info.
=> Get profile info

accounts/tests.py, accounts/urls.py, accounts/views.py, search/tests.py, settings/base.py
Hi @YPCrumble, this PR is used for changing to use session authentication for requests from the extension.
=> Use session authentication for requests from extension

.env.example, emails/jobs/hourly/send_welcome_email.py, emails/mailer.py, emails/tests.py, emails/utils.py, requirements/base.txt, requirements/local.txt, settings/base.py
Hi @YPCrumble, this PR is used for adding email sender and sending welcome email six hours after the user signs up for Guppy.
=> Add email sender and send welcome email

guppy/templates/500.html, settings/production.py
Hi @YPCrumble, this PR is used for adding files for the production site.
Please help me to review!
=> Add files for production site

.env.example, accounts/context_processors.py, frontend/package.json, requirements/base.txt, settings/base.py, settings/staging.py, templates/index.html
Hi @YPCrumble, this PR is used for adding Sentry for Guppy staging.
=> Add Sentry for Staging

accounts/admin.py, accounts/models.py, accounts/templates/accounts/profile.html, accounts/tests.py, accounts/urls.py, accounts/views.py
Hi @YPCrumble, this PR is used for adding the payout requests management.
Please help me to review!
=> Add payout requests management

templates/index.html
Hi @YPCrumble, this PR is used for moving login signup buttons to the right side.
=> Move login signup buttons to the right

frontend/css/style.css, guppy/templates/guppy/privacy_policy.html, guppy/templates/guppy/terms_of_service.html, guppy/urls.py, guppy/views.py, settings/base.py, templates/index.html
Hi @YPCrumble, this PR is used for adding privacy policy and terms of service pages.
=> Add privacy policy and terms of service page

accounts/templates/accounts/signup.html, accounts/tests.py, accounts/views.py, requirements/base.txt, settings/base.py
Hi @YPCrumble, this PR is used for adding honeypot.
=> Add honeypot

accounts/forms.py, accounts/templates/accounts/profile.html, accounts/templates/accounts/userprofile_form.html, accounts/tests.py, accounts/urls.py, accounts/views.py
Hi @YPCrumble, this PR is used for adding the profile edit page.
=> Add the profile edit page

accounts/models.py, accounts/tests.py, accounts/views.py
Hi @YPCrumble, this PR is used for adjusting how the waitlist work.
=> Adjust how the waitlist work

frontend/css/style.css, search/templates/search/home.html
Hi @YPCrumble, this PR is used for updating the homepage.
=> Update the homepage

guppy/templates/guppy/privacy_policy.html, guppy/templates/guppy/terms_of_service.html
@autn I want to make sure linebreaks look good on these pages - would you review and update if necessary for the styling?
I think it's fun to have such a simple TOS and PP - it feels very "honest". Big companies like Google and FB (in reality) don't respect users' privacy, but their TOS and PP are hundreds of pages long. This is much more forthright IMO :D. It's something I want to continue to implement for Guppy moving forward. cc @truonghn 
Thanks!
=> Update TOS and Privacy Policy.

.github/workflows/mypy.yml, .github/workflows/pylint.yml, requirements/base.txt, search/templates/search/home.html, settings/base.py
Hi @YPCrumble, this PR is used for adding caching to the guppy home page.
Would you help me to review.
=> Cache the homepage

frontend/css/style.css, search/templates/search/home.html
Also adds padding to the footer.
=> Add a shadow to text on the home page to improve its readability.
